name       : uthash
version    : 2.0.1
release    : 3
source     :
    - https://github.com/troydhanson/uthash/archive/v2.0.1.tar.gz : 613b95fcc368b7d015ad2d0802313277012f50c4ac290c3dfc142d42ebea3337
license    : BSD-3-Clause
component  : programming
summary    : hash table for C
description: |
    A hash table for C structures
setup      : |
    %apply_patches
build      : |
    pushd libut
    %make DESTDIR=$installdir LIBDIR=%libdir%
    popd
install    : |
    pushd libut
    %make_install DESTDIR=$installdir LIBDIR=%libdir%
    popd
check      : |
    pushd libut/tests
    make
    popd
    pushd tests
    ./all_funcs
    popd
